<a href="https://colab.research.google.com/github/m99Tanishq/ann/blob/main/Word_Emdedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8794, 7735, 2955, 1617], [8794, 7735, 2955, 5293], [8794, 2114, 2955, 1752], [2650, 7051, 5099, 6206, 8886], [2650, 7051, 5099, 6206, 5317], [4243, 8794, 4167, 2955, 8939], [5898, 5659, 3139, 6206]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8794 7735 2955 1617]
 [   0    0    0    0 8794 7735 2955 5293]
 [   0    0    0    0 8794 2114 2955 1752]
 [   0    0    0 2650 7051 5099 6206 8886]
 [   0    0    0 2650 7051 5099 6206 5317]
 [   0    0    0 4243 8794 4167 2955 8939]
 [   0    0    0    0 5898 5659 3139 6206]]


In [12]:
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 197ms/step
[[[-2.4338031e-02 -4.9584817e-02  2.8128576e-02 -2.2823060e-02
    3.2759335e-02 -1.4955737e-02 -1.0507323e-02  4.1930351e-02
    3.3769514e-02 -4.8319828e-02]
  [-2.4338031e-02 -4.9584817e-02  2.8128576e-02 -2.2823060e-02
    3.2759335e-02 -1.4955737e-02 -1.0507323e-02  4.1930351e-02
    3.3769514e-02 -4.8319828e-02]
  [-2.4338031e-02 -4.9584817e-02  2.8128576e-02 -2.2823060e-02
    3.2759335e-02 -1.4955737e-02 -1.0507323e-02  4.1930351e-02
    3.3769514e-02 -4.8319828e-02]
  [-2.4338031e-02 -4.9584817e-02  2.8128576e-02 -2.2823060e-02
    3.2759335e-02 -1.4955737e-02 -1.0507323e-02  4.1930351e-02
    3.3769514e-02 -4.8319828e-02]
  [-2.1225680e-02  1.8788684e-02  2.3280326e-02 -1.6829111e-02
    9.7843520e-03  2.3017574e-02 -3.2129765e-02 -4.0920783e-02
    4.7757477e-04  7.2197989e-04]
  [ 1.4725458e-02  1.8492285e-02  4.1272882e-02  2.8936300e-02
    1.4824558e-02 -3.9785616e-03 -1.4203511e-02  4.7148060e-02
    3.6844578e-02  6.

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 6654,  998, 8966, 1609])

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]